import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const js=ts.transpileModule(fs.readFileSync('lib/directfuel-accounting-report.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {accountingReport}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const fuel=(id,medicaoId,qt,total)=>({id,medicaoId,postoId:'S',unidadeId:'U',produtoId:'P',qt,preco:2,total,data:'2026-09-01'});
const state={postos:[{id:'S',sap:'000123',cnpj:'123',fantasia:'Posto'}],unidades:[{id:'U',nome:'Filial',centroSap:'ZAA1'}],produtos:[{id:'P',sap:'35012674',descricao:'Arla'}],medicoes:[{id:'M1',numero:'639781-2',status:'Aprovada',itens:['A','A'],notasFiscais:[{numero:'639781',serie:'2',emissao:'2026-09-01',abastecimentoIds:['A','ADDED']}]},{id:'M2',numero:'640480-2',status:'Aprovada',itens:['B'],notasFiscais:[{numero:'640480',serie:'2',emissao:'2026-09-01',abastecimentoIds:['B']}]}],abastecimentos:[fuel('A','M1',10,20),fuel('B','M2',20,40),fuel('ADDED','M1',5,10),fuel('UNRELATED',null,999,1998)],sapReturns:[{measurementId:'M1',invoiceKey:'639781-2',status:'success',purchaseOrder:'4502936107',postingDate:'2026-09-02'},{measurementId:'M2',invoiceKey:'640480-2',status:'success',purchaseOrder:'4502936108',postingDate:'2026-09-03'}]};
test('selected 639781-2 and 640480-2 include purchase orders, posting dates and only explicit fuel links',()=>{const before=JSON.stringify(state),r=accountingReport(state,['M1','M2','M1']);assert.deepEqual(r.rows.map(x=>x['ID Abastecimento']),['A','ADDED','B']);assert.deepEqual(r.summary,{measurements:2,count:3,volume:35,total:70});assert.deepEqual(r.subtotals.map(x=>[x.count,x.volume,x.total]),[[2,15,30],[1,20,40]]);assert.equal(r.rows[0]['Pedido de Compra'],'4502936107');assert.equal(r.rows[0]['Data Lançamento NF SAP'],'2026-09-02');assert.equal(r.rows[1]['Pedido de Compra'],'4502936107');assert.equal(JSON.stringify(state),before);assert.equal(accountingReport(state,['M2']).summary.count,1);});
test('conflicting and missing explicit relationships fail instead of silently duplicating',()=>{const s=structuredClone(state);s.medicoes[1].itens.push('A');assert.throws(()=>accountingReport(s,['M1','M2']),/conflitante/);s.medicoes[1].itens=['MISSING'];assert.throws(()=>accountingReport(s,['M2']),/não encontrado/);});
test('Excel round trip preserves purchase order, posting date, totals and filenames',()=>{const ctx={window:{},console,Date};vm.createContext(ctx);vm.runInContext(fs.readFileSync('public/gekon-xlsx.js','utf8'),ctx);vm.runInContext(fs.readFileSync('public/directfuel-accounting-report.js','utf8'),ctx);const r=accountingReport(state,['M1','M2']),api=ctx.window.DirectFuelAccountingExcel;const data=ctx.XLSX.write(api.workbook(r),{type:'array',bookType:'xlsx'}),book=ctx.XLSX.read(data,{type:'array',cellDates:true}),rows=ctx.XLSX.utils.sheet_to_json(book.Sheets.Abastecimentos);assert.equal(rows.length,3);assert.equal(rows[0]['Pedido de Compra'],'4502936107');assert.equal(rows[0]['Data Lançamento NF SAP'] instanceof Date,true);assert.equal(rows[0]['Fornecedor SAP'],'000123');assert.equal(rows.reduce((s,r)=>s+r['Valor total'],0),70);assert.match(api.filename(r),/^Abastecimentos_Pedidos_Compra_\d{4}-\d{2}-\d{2}\.xlsx$/);assert.equal(api.filename(accountingReport(state,['M1'])),'Abastecimentos_639781-2.xlsx');});
test('purchase order filter uses active relationships; selection is per measurement across multiple NF rows',()=>{const ctx={window:{},console,Date};vm.createContext(ctx);vm.runInContext(fs.readFileSync('public/directfuel-accounting-report.js','utf8'),ctx);const api=ctx.window.DirectFuelAccountingFilters;const s={sapReturns:[{measurementId:'M1',purchaseOrder:'4501',voided:true},{measurementId:'M1',purchaseOrder:'4502'},{measurementId:'M2',purchaseOrder:'4503'}]};assert.equal(api.matchPurchaseOrder(api.purchaseOrders(s,'M1'),'4501',[]),false);assert.equal(api.matchPurchaseOrder(api.purchaseOrders(s,'M1'),'4502',['4502','4503']),true);assert.equal(api.matchPurchaseOrder(api.purchaseOrders(s,'M3'),'',['__none']),true);assert.equal(api.matchPurchaseOrder(api.purchaseOrders(s,'M1'),'',['__none']),false);const selection=api.selection();selection.toggle('M1',true);selection.toggle('M1',true);assert.equal(selection.selected.size,1);selection.all(new Set(['M1','M2']),true);assert.equal(selection.selected.size,2);selection.reconcile(new Set(['M2']));assert.equal(selection.selected.size,1);assert.ok(selection.selected.has('M2'));selection.all(new Set(['M2']),false);assert.equal(selection.selected.size,0);});

test('filtered accounting and SAP layout exports preserve the accepted headers and identifier types',()=>{
 const ctx={window:{},console,Date};vm.createContext(ctx);vm.runInContext(fs.readFileSync('public/gekon-xlsx.js','utf8'),ctx);vm.runInContext(fs.readFileSync('public/directfuel-accounting-report.js','utf8'),ctx);const api=ctx.window.DirectFuelAccountingExcel;
 const invoices=[{m:state.medicoes[0],n:state.medicoes[0].notasFiscais[0],key:'639781-2',number:'639781',date:'2026-09-01'}];
 const accounting=api.accountingRows(state,invoices);assert.equal(accounting.length,1);assert.equal(accounting[0]['Fornecedor SAP'],'000123');assert.equal(accounting[0]['Pedido de Compra'],'4502936107');
 const layout=api.sapLayoutRows(state,invoices);assert.deepEqual(Object.keys(layout[0]),['Documento de Compras','Data de Criação do Pedido','Fornecedor do Pedido','Nº da Nota Fiscal','Data do Lançamento da Nota Fiscal']);assert.equal(layout[0]['Fornecedor do Pedido'],'000123');assert.equal(layout[0]['Nº da Nota Fiscal'],'639781');
 const data=ctx.XLSX.write(api.rowsWorkbook(layout,'Carga SAP'),{type:'array',bookType:'xlsx'}),book=ctx.XLSX.read(data,{type:'array',cellDates:true}),rows=ctx.XLSX.utils.sheet_to_json(book.Sheets['Carga SAP']);assert.equal(rows[0]['Documento de Compras'],'4502936107');assert.equal(rows[0]['Fornecedor do Pedido'],'000123');assert.equal(rows[0]['Data do Lançamento da Nota Fiscal'] instanceof Date,true);
 vm.runInContext(fs.readFileSync('public/directfuel-sap-return.js','utf8'),ctx);const parsed=ctx.window.DirectFuelSapReturn.parse(ctx.XLSX.utils.sheet_to_json(book.Sheets['Carga SAP'],{header:1,defval:'',raw:true}),'Carga SAP');assert.equal(parsed[0].status,'success');assert.equal(parsed[0].invoiceNumber,'639781');assert.equal(parsed[0].supplier,'123');
});
