import { env } from 'cloudflare:workers';
import { requireVixparUser, WORKSPACE_ID } from '@/lib/directfuel-access';
import { hasPermission, isAdmin, hasAction } from '@/lib/directfuel-security';
import { auditSummary, defaults, simpleParameters, validate, calcularAuditoriaVolume, cards, statuses, plate, type Row, type Params } from '@/lib/directfuel-volume';
import { decodeStoredState } from '@/lib/directfuel-state-codec';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'cache-control':'private, no-store'}});
async function config(){const r=await env.DB.prepare('SELECT * FROM volume_parameters WHERE workspace_id=? ORDER BY version DESC LIMIT 1').bind(WORKSPACE_ID).first<Row>();return {parameters:r?simpleParameters(JSON.parse(String(r.data))):defaults,version:Number(r?.version||0)};}
export async function GET(){const a=await requireVixparUser();if('error'in a)return json({error:a.error},a.status);if(!hasPermission(a,'audit'))return json({error:'Sem acesso à auditoria.'},403);try {return json({...await config(),defaults,canConfigure:hasAction(a,'audit','editar'),canReview:hasAction(a,'audit','editar'),statuses});}catch(e){console.error('Volume audit read',e);return json({error:'Não foi possível carregar a auditoria. Tente novamente.'},503);}}
async function source(){const [state,ticket]=await Promise.all([env.DB.prepare('SELECT data FROM app_state WHERE workspace_id=?').bind(WORKSPACE_ID).first<{data:string}>(),env.DB.prepare('SELECT id,transaction_code,occurred_on,occurred_time,product,plate,liters,final_value,station_name,driver_name FROM ticketlog_fuelings WHERE workspace_id=?').bind(WORKSPACE_ID).all<Row>()]);const s=state?await decodeStoredState<Record<string,Row[]>>(state.data):{};const direct:Row[]=(s.abastecimentos||[]).map((r:Row)=>({...r,fonte:String(r.origem||'').toLowerCase().includes('ticket')?'Ticketlog':'DirectFuel',canalOrigem:String(r.origem||'DirectFuel'),reference:String(r.id||''),produto:(s.produtos||[]).find((p:Row)=>p.id===r.produtoId)?.curta||r.produto||'',key:r.id?'direct:'+String(r.id):'direct:fingerprint:'+JSON.stringify([plate(r.placa),r.data,r.hora,r.postoId,r.qt,r.total,r.motorista]),posto:(s.postos||[]).find((p:Row)=>p.id===r.postoId)?.fantasia||r.postoId}));const imported:Row[]=ticket.results.map(r=>({fonte:'Ticketlog',canalOrigem:'Importação Ticketlog',reference:String(r.transaction_code),key:'ticket:'+r.transaction_code,id:r.id,placa:r.plate,data:String(r.occurred_on).slice(0,10),produto:r.product,hora:r.occurred_time||String(r.occurred_on).match(/[T ](\d{2}:\d{2}(?::\d{2})?)/)?.[1]||'',qt:r.liters,total:r.final_value,posto:r.station_name,motorista:r.driver_name}));return {rows:[...direct,...imported],fleet:s.frota||[]};}
export async function POST(request:Request){const a=await requireVixparUser();if('error'in a)return json({error:a.error},a.status);if(!hasPermission(a,'audit'))return json({error:'Sem acesso à auditoria.'},403);if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return json({error:'Origem inválida.'},403);
try {const body=await request.json() as {action:string;parameters:Params;version:number;key:string;status:string;observation:string;updatedAt?:string;filters?:Record<string,string|string[]>},current=await config(),now=new Date().toISOString(),email=a.user.email;
 if(body.action==='history'){const r=await env.DB.prepare('SELECT version,changes,created_at,created_by FROM volume_parameters WHERE workspace_id=? ORDER BY version DESC LIMIT 200').bind(WORKSPACE_ID).all();return json({history:r.results});}
 if(body.action==='save'){
 if(!hasAction(a,'audit','editar'))return json({error:'É necessária permissão de editar auditoria para calibrar parâmetros.'},403);const error=validate(body.parameters);if(error)return json({error},400);if(body.version!==current.version)return json({error:'Parâmetros alterados por outro usuário. Reabra a tela antes de salvar.'},409);
 const changes:Row[]=[];for(const [section,value] of Object.entries(body.parameters)){if(Array.isArray(value)){if(JSON.stringify(value)!==JSON.stringify(current.parameters[section as keyof Params]))changes.push({parameter:section,before:current.parameters[section as keyof Params],after:value});}else for(const [key,next] of Object.entries(value as Row)){const old=(current.parameters[section as keyof Params] as unknown as Row)?.[key];if(old!==next)changes.push({parameter:`${section}.${key}`,before:old,after:next});}}
 if(!changes.length)return json(current);
 try {await env.DB.prepare('INSERT INTO volume_parameters (id,workspace_id,version,data,changes,created_at,created_by) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),WORKSPACE_ID,current.version+1,JSON.stringify(body.parameters),JSON.stringify(changes),now,email).run();}catch(e){if(String(e).includes('UNIQUE'))return json({error:'Outro usuário salvou os parâmetros. Reabra a tela.'},409);throw e;}return json({parameters:body.parameters,version:current.version+1});
 }
 if(body.action==='review'){
 if(!hasAction(a,'audit','editar'))return json({error:'Sem permissão para tratar ocorrências.'},403);if(!statuses.includes(body.status)||typeof body.key!=='string'||typeof body.observation!=='string'||body.observation.length>3000)return json({error:'Tratamento inválido.'},400);
 const data=await source();if(!data.rows.some(r=>r.key===body.key))return json({error:'Abastecimento não encontrado.'},404);
 const old=await env.DB.prepare('SELECT * FROM volume_reviews WHERE workspace_id=? AND record_key=?').bind(WORKSPACE_ID,body.key).first<Row>();if((old?.updated_at||null)!==(body.updatedAt||null))return json({error:'Ocorrência tratada por outro usuário. Atualize os resultados.'},409);
 const result=await env.DB.prepare('INSERT INTO volume_reviews (id,workspace_id,record_key,status,observation,updated_at,updated_by) VALUES (?,?,?,?,?,?,?) ON CONFLICT(workspace_id,record_key) DO UPDATE SET status=excluded.status,observation=excluded.observation,updated_at=excluded.updated_at,updated_by=excluded.updated_by WHERE volume_reviews.updated_at=?').bind(crypto.randomUUID(),WORKSPACE_ID,body.key,body.status,body.observation,now,email,body.updatedAt||'').run();if(!result.meta.changes)return json({error:'Conflito de tratamento. Atualize os resultados.'},409);return json({review:{record_key:body.key,status:body.status,observation:body.observation,updated_at:now,updated_by:email}});
 }
 if(!['calculate','simulate','summary'].includes(body.action))return json({error:'Ação inválida.'},400);
 const p=body.action==='simulate'?body.parameters:current.parameters,error=validate(p);if(error)return json({error},400);
 const data=await source(),raw=body.filters||{},one=(key:string)=>{const value=raw[key];return Array.isArray(value)?String(value[0]||''):String(value||'');},many=(key:string)=>{const value=raw[key];return (Array.isArray(value)?value:[value]).filter(Boolean).map(String);};
 const f={from:one('from'),to:one('to'),plate:body.action==='summary'?'':one('plate'),station:body.action==='summary'?'':one('station'),driver:body.action==='summary'?'':one('driver'),source:body.action==='summary'?'':one('source'),product:body.action==='summary'?'':one('product'),auditType:body.action==='summary'?'':one('auditType'),classification:body.action==='summary'?[]:many('classification'),status:body.action==='summary'?[]:many('status')};
 if(f.from&&f.to&&f.from>f.to)return json({error:'Data inicial deve ser anterior à data final.'},400);
 const selected=data.rows.filter(r=>(!f.from||String(r.data)>=f.from)&&(!f.to||String(r.data)<=f.to)&&(!f.plate||plate(r.placa).includes(plate(f.plate)))&&(!f.station||String(r.posto||'').toLowerCase().includes(String(f.station).toLowerCase()))&&(!f.driver||String(r.motorista||'').toLowerCase().includes(String(f.driver).toLowerCase()))),plates=new Set(selected.map(r=>plate(r.placa))),keys=new Set(selected.map(r=>r.key));
 const relevant=data.rows.filter(r=>plates.has(plate(r.placa))&&(!f.to||String(r.data)<=f.to));const reviews=await env.DB.prepare('SELECT * FROM volume_reviews WHERE workspace_id=?').bind(WORKSPACE_ID).all<Row>(),reviewMap=new Map(reviews.results.map(r=>[r.record_key,r]));
 const run=(params:Params)=>calcularAuditoriaVolume(relevant,data.fleet,params).filter(r=>keys.has(r.key)).map(r=>({...r,review:reviewMap.get(r.key)||null})).filter(r=>(!f.classification.length||f.classification.includes(f.auditType==='window'?r.windowClass:r.capacityClass))&&(!f.status.length||f.status.includes(String(r.review?.status||'Pendente')))&&(!f.source||r.fonte===f.source)&&(!f.product||r.productGroup===f.product));
 const rows=run(p);if(body.action==='summary')return json({summary:auditSummary(rows),calculatedAt:now,version:current.version});return json({rows:body.action==='calculate'?rows:[],cards:cards(rows,f.auditType),before:body.action==='simulate'?cards(run(current.parameters),f.auditType):null,version:current.version,calculatedAt:now});
}catch(e){console.error('Volume audit operation',e);return json({error:'Não foi possível concluir. Os dados preenchidos foram preservados; tente novamente.'},503);}}
